-- Databricks notebook source
-- MAGIC %python
-- MAGIC # scripts/extract_sql.py
-- MAGIC import json
-- MAGIC import sys
-- MAGIC
-- MAGIC def extract_sql_from_notebook(filepath):
-- MAGIC     try:
-- MAGIC         with open(filepath, 'r', encoding='utf-8') as f:
-- MAGIC             data = json.load(f)
-- MAGIC         
-- MAGIC         sql_commands = []
-- MAGIC         for cell in data.get('cells', []):
-- MAGIC             if cell.get('cell_type') == 'code':
-- MAGIC                 source = cell.get('source', [])
-- MAGIC                 cell_text = ''.join(source).strip()
-- MAGIC                 if cell_text.startswith('%sql'):
-- MAGIC                     # Remove o '%sql' e limpa os espaços e quebras de linha extras
-- MAGIC                     clean_sql = cell_text.replace('%sql', '', 1).strip()
-- MAGIC                     if clean_sql:
-- MAGIC                         sql_commands.append(clean_sql)
-- MAGIC         
-- MAGIC         # Junta todas as células SQL encontradas separando-as por quebra de linha
-- MAGIC         return '\n;\n'.join(sql_commands)
-- MAGIC     except Exception as e:
-- MAGIC         print(f"Erro ao ler o arquivo {filepath}: {e}", file=sys.stderr)
-- MAGIC         sys.exit(1)
-- MAGIC
-- MAGIC if __name__ == "__main__":
-- MAGIC     if len(sys.argv) < 2:
-- MAGIC         print("Uso: python extract_sql.py <caminho_do_notebook.ipynb>", file=sys.stderr)
-- MAGIC         sys.exit(1)
-- MAGIC     
-- MAGIC     notebook_path = sys.argv[1]
-- MAGIC     print(extract_sql_from_notebook(notebook_path))