name: Deploy DDL

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    paths:
      - 'ddl/**'

  push:
    branches:
      - dev
      - main
    paths:
      - 'ddl/**'

  workflow_dispatch:

jobs:
  deploy-schema:
    runs-on: ubuntu-latest
    
    env:
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
      DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Databricks CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh

      - name: Execute DDL via SQL Statement Execution API
        run: |
          # Certifique-se de que o arquivo DDL não contém a linha '%sql'
          SQL_CONTENT=$(cat ./ddl/schema_financas/schema_financas_000001)
          
          databricks statement-execution execute \
            --warehouse-id "2d82741f78a6da87" \
            --statement "$SQL_CONTENT"