name: Deploy Scripts

on:
  push:
    branches:
      - dev
      - main
    paths:
      - 'dml/**'          # Dispara apenas quando você atualizar scripts de carga

  workflow_dispatch:      # Permite forçar a sincronização manualmente se quiser

jobs:
  sync-git-folder:
    runs-on: ubuntu-latest
   
    env:
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
      DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
      # O caminho da sua pasta de usuário onde o Repositório está clonado no Databricks
      DATABRICKS_REPO_PATH: "/Workspace/Users/mhenrique.sousa@gmail.com/mcunha-dados-product-financas-fiis"

    steps:
      - name: Install Databricks CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh

      - name: Sync Git Folder on Databricks (Git Pull)
        run: |
          # Limpa o protocolo https:// do host para o Databricks CLI funcionar
          CLEAN_HOST=$(echo "$DATABRICKS_HOST" | sed -e 's|^https://||' -e 's|^http://||')
          export DATABRICKS_HOST="https://$CLEAN_HOST"
          export DATABRICKS_TOKEN="$DATABRICKS_TOKEN"

          echo "Sincronizando repositório no Databricks..."
          # Faz o Databricks dar um Git Pull na branch correta para atualizar os arquivos físicos lá dentro
          databricks repos update "$DATABRICKS_REPO_PATH" --branch "${{ github.ref_name }}"
          
          echo "✅ Repositório atualizado com sucesso no Databricks Git Folders!"